### ISSUE TITLE
Sadly, just doesn't seem to work.

### ISSUE THREAD

**Issue by AndrueCope** [dotMorten/XamarinFormsControls#19]
### Description

I've just tried it under Android and there's no query button. It just looks like a normal Entry control. If I type text something appears underneath the entered text, mostly obscured by the virtual keyboard, but is empty.

### Steps to Reproduce

I just added it to my form as part of a datatemplate:

`<DataTemplate x:Key="PictureMediaEditorInformationTemplate" x:DataType="mediaeditorinformation:PictureMediaEditorInformation">
              <ViewCell>
                <StackLayout Orientation="Vertical"  Padding="4,0,0,0">
                    <Label Text="{Binding LabelContent}" Margin="0,0,0,4"/>
                    <StackLayout Orientation="Vertical">
                        <StackLayout Orientation="Vertical">
                            <Label Text="{Binding LabelTitle}" Margin="0,0,0,4"/>
                            <Editor Text="{Binding Title}" />
                            <Image Source="{Binding VisibleImage, Converter={StaticResource MobileImageProcyToImageConverter}}" Aspect="AspectFit"
                                   WidthRequest="{Binding Source={StaticResource PlatformCustomisations}, Path=ImageThumbWidthHeight}"
                                   HeightRequest="{Binding Source={StaticResource PlatformCustomisations}, Path=ImageThumbWidthHeight}"/>
                            <controls:FontAwesomeButton Command="{Binding ChooseImageCommand}" Text="{Binding ChooseImageCaption}"/>
                            <forms:AutoSuggestBox PlaceholderText="{Binding LabelTags}" Text="{Binding NewTagText}"
                                                  TextChanged="AutoSuggestBox_OnTextChanged"/>
                            <controls:FontAwesomeButton Command="{Binding AddTagCommand}" Text="{x:Static controls:Icon.FAPlus}" />
                        </StackLayout>
                    </StackLayout>
                </StackLayout>
              </ViewCell>
          </DataTemplate>`

### Expected Behavior

I expected autocomplete functionality.

### Actual Behavior

Just got an entry field with empty and poorly rendered drop down.

### Basic Information

- Version with issue: 1.0.14
- Last known good version:
- IDE: vs 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:Samsung S7

**Comment by dotMorten** [comment]
Does the sample in this repo work for you?

**Comment by AndrueCope** [comment]
Unfortunately it doesn't build for me at all:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'dotMorten.Xamarin.Forms.AutoSuggestBox, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'dotMorten.Xamarin.Forms.AutoSuggestBox.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AutoSuggestBoxSample.Android
